This test case tests that shards added to the system with already-failed processes can still function

# Start clusters
python paxos/send.py 2 0 config/replica/localFive1 -n 2 -c 0
python paxos/send.py 2 1 config/replica/localFive1 -n 2 -c 0
python paxos/send.py 2 2 config/replica/localFive1 -n 2 -c 0
python paxos/send.py 2 3 config/replica/localFive1 -n 2 -c 0
python paxos/send.py 2 4 config/replica/localFive1 -n 2 -c 0

python paxos/send.py 1 0 config/replica/local2 -n 2 -c 1
python paxos/send.py 1 1 config/replica/local2 -n 2 -c 1
python paxos/send.py 1 2 config/replica/local2 -n 2 -c 1

# Initialize cluster with one failed node to be added later
python paxos/send.py 1 0 config/replica/local3
python paxos/send.py 1 1 config/replica/local3

# Initialize cluster with primary failed to be added later
python paxos/send.py 1 1 config/replica/local4
python paxos/send.py 1 2 config/replica/local4

# Start master and client
python startMaster.py config/master/twoNodeLocal
python startClient config/client/clientLocal


# Add shards with failed replicas
add_shard 127.0.0.1,7400 127.0.0.1,7401 127.0.0.1,7402
add_shard 127.0.0.1,7500 127.0.0.1,7501 127.0.0.1,7502

# Keys
6 9
1 2 3 4 5 7 8

# Key assignments
6 9 
2 3 5 8 
1 4 7

# After
6 9 
3 5 8 
1 4 7
2 